/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  SchedulingData,
} from './models/scheduling-data.model';
import {
  Professional,
} from './models/professional.model';


export namespace Components {

  interface AppScheduling {
    'data': SchedulingData[];
  }
  interface AppSchedulingAttributes extends StencilHTMLAttributes {
    'data'?: SchedulingData[];
    'onOnScheduleUpdated'?: (event: CustomEvent) => void;
  }

  interface DatePicker {}
  interface DatePickerAttributes extends StencilHTMLAttributes {
    'onOnDateUpdated'?: (event: CustomEvent) => void;
  }

  interface ProfessionalPicker {
    'professionals': Professional[];
  }
  interface ProfessionalPickerAttributes extends StencilHTMLAttributes {
    'onOnProfessionalUpdated'?: (event: CustomEvent) => void;
    'professionals'?: Professional[];
  }

  interface TimePicker {
    'availableTimes': Date[];
    'resetSchedules': () => void;
  }
  interface TimePickerAttributes extends StencilHTMLAttributes {
    'availableTimes'?: Date[];
    'onOnTimeUpdated'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppScheduling': Components.AppScheduling;
    'DatePicker': Components.DatePicker;
    'ProfessionalPicker': Components.ProfessionalPicker;
    'TimePicker': Components.TimePicker;
  }

  interface StencilIntrinsicElements {
    'app-scheduling': Components.AppSchedulingAttributes;
    'date-picker': Components.DatePickerAttributes;
    'professional-picker': Components.ProfessionalPickerAttributes;
    'time-picker': Components.TimePickerAttributes;
  }


  interface HTMLAppSchedulingElement extends Components.AppScheduling, HTMLStencilElement {}
  var HTMLAppSchedulingElement: {
    prototype: HTMLAppSchedulingElement;
    new (): HTMLAppSchedulingElement;
  };

  interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {}
  var HTMLDatePickerElement: {
    prototype: HTMLDatePickerElement;
    new (): HTMLDatePickerElement;
  };

  interface HTMLProfessionalPickerElement extends Components.ProfessionalPicker, HTMLStencilElement {}
  var HTMLProfessionalPickerElement: {
    prototype: HTMLProfessionalPickerElement;
    new (): HTMLProfessionalPickerElement;
  };

  interface HTMLTimePickerElement extends Components.TimePicker, HTMLStencilElement {}
  var HTMLTimePickerElement: {
    prototype: HTMLTimePickerElement;
    new (): HTMLTimePickerElement;
  };

  interface HTMLElementTagNameMap {
    'app-scheduling': HTMLAppSchedulingElement
    'date-picker': HTMLDatePickerElement
    'professional-picker': HTMLProfessionalPickerElement
    'time-picker': HTMLTimePickerElement
  }

  interface ElementTagNameMap {
    'app-scheduling': HTMLAppSchedulingElement;
    'date-picker': HTMLDatePickerElement;
    'professional-picker': HTMLProfessionalPickerElement;
    'time-picker': HTMLTimePickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
