/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  SchedulingData,
} from './models/scheduling-data.model';
import {
  Professional,
} from './models/professional.model';
import {
  SchedulingResponse,
} from './models/scheduling-response.model';


export namespace Components {

  interface AppScheduling {
    'schedulingData': SchedulingData;
    'selectedSchedules': Date[];
  }
  interface AppSchedulingAttributes extends StencilHTMLAttributes {
    'onOnScheduleUpdated'?: (event: CustomEvent) => void;
    'schedulingData'?: SchedulingData;
    'selectedSchedules'?: Date[];
  }

  interface DatePicker {}
  interface DatePickerAttributes extends StencilHTMLAttributes {
    'onOnDateUpdated'?: (event: CustomEvent) => void;
  }

  interface SchedulesOverview {
    'professional': Professional;
    'scheduling': SchedulingResponse;
  }
  interface SchedulesOverviewAttributes extends StencilHTMLAttributes {
    'professional'?: Professional;
    'scheduling'?: SchedulingResponse;
  }

  interface TimePicker {
    'availableTimes': Date[];
    'selectedTimes': Date[];
  }
  interface TimePickerAttributes extends StencilHTMLAttributes {
    'availableTimes'?: Date[];
    'onOnTimeUpdated'?: (event: CustomEvent) => void;
    'selectedTimes'?: Date[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppScheduling': Components.AppScheduling;
    'DatePicker': Components.DatePicker;
    'SchedulesOverview': Components.SchedulesOverview;
    'TimePicker': Components.TimePicker;
  }

  interface StencilIntrinsicElements {
    'app-scheduling': Components.AppSchedulingAttributes;
    'date-picker': Components.DatePickerAttributes;
    'schedules-overview': Components.SchedulesOverviewAttributes;
    'time-picker': Components.TimePickerAttributes;
  }


  interface HTMLAppSchedulingElement extends Components.AppScheduling, HTMLStencilElement {}
  var HTMLAppSchedulingElement: {
    prototype: HTMLAppSchedulingElement;
    new (): HTMLAppSchedulingElement;
  };

  interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {}
  var HTMLDatePickerElement: {
    prototype: HTMLDatePickerElement;
    new (): HTMLDatePickerElement;
  };

  interface HTMLSchedulesOverviewElement extends Components.SchedulesOverview, HTMLStencilElement {}
  var HTMLSchedulesOverviewElement: {
    prototype: HTMLSchedulesOverviewElement;
    new (): HTMLSchedulesOverviewElement;
  };

  interface HTMLTimePickerElement extends Components.TimePicker, HTMLStencilElement {}
  var HTMLTimePickerElement: {
    prototype: HTMLTimePickerElement;
    new (): HTMLTimePickerElement;
  };

  interface HTMLElementTagNameMap {
    'app-scheduling': HTMLAppSchedulingElement
    'date-picker': HTMLDatePickerElement
    'schedules-overview': HTMLSchedulesOverviewElement
    'time-picker': HTMLTimePickerElement
  }

  interface ElementTagNameMap {
    'app-scheduling': HTMLAppSchedulingElement;
    'date-picker': HTMLDatePickerElement;
    'schedules-overview': HTMLSchedulesOverviewElement;
    'time-picker': HTMLTimePickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
